# Merged on top of default API config + Role config file
# See: # https://access.redhat.com/documentation/en-us/red_hat_quay/3/html/manage_red_hat_quay/quay-schema
FEATURE_MAILING: true
MAIL_DEFAULT_SENDER: is-monitoring@example.com
MAIL_PORT: 25
MAIL_SERVER: apprelay.corp.example.com
MAIL_USE_TLS: false

SUPER_USERS: [jcole, somebody]

DISTRIBUTED_STORAGE_CONFIG:
  default:
  - AzureStorage
  - { azure_account_key: "{{ secrets.azure_account_key }}", azure_account_name: quayblobaccount, azure_container: quay, storage_path: /datastorage/registry }
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
DISTRIBUTED_STORAGE_PREFERENCE: [default]

AUTHENTICATION_TYPE: LDAP
LDAP_ADMIN_DN: CN=ldapcpsvc,OU=ServiceAccounts,OU=US,OU=Enterprise,DC=corp,DC=example,DC=com
LDAP_ADMIN_PASSWD: "{{ secrets.ldap_password }}"
LDAP_BASE_DN: [DC=corp, DC=example, DC=com]
LDAP_EMAIL_ATTR: mail
LDAP_UID_ATTR: sAMAccountName
LDAP_URI: ldap://ad.corp.example.com?sizelimit=0
LDAP_USER_RDN: [CN=Users]
LDAP_SECONDARY_USER_RDNS: []

FEATURE_USERNAME_CONFIRMATION: false
