inventory_name: "{{ inventory_dir.split('/') | last }}"

secrets: "{{ lookup('file', '{{ inventory_dir }}/../../secrets/{{ inventory_name }}/secrets.yml') | from_yaml }}"

# The following is used by the prestup-* playbooks and rhel_vm role
dns_search: search corp.example.com

dns_servers:
- 192.168.200.1
- 192.168.200.2
- 192.168.200.22
- 192.168.200.24

epel_repo: EPEL_EPEL_RHEL7_x86_64
