# base config will be loaded from server,
# next  {{ inventory_dir }}/../../roles/quay/files/quay/config.yaml will be overlayed on top
# finally, the following "quay_config" object will be layered on top.
# https://access.redhat.com/documentation/en-us/red_hat_quay/3/html/manage_red_hat_quay/quay-schema
quay_config: "{{ lookup('template', '{{ inventory_dir }}/../../files/{{ inventory_name }}/quay/config.yaml') | from_yaml }}"

quay_cert_file: "{{ inventory_dir }}/../../files/{{ inventory_name }}/quay/{{ quay_hostname }}.crt"
quay_key_file: "{{ inventory_dir }}/../../files/{{ inventory_name }}/quay/{{ quay_hostname }}.key"

# Wildcards accepted
# All filenames should be unique
quay_ca_files:
- "{{ inventory_dir }}/../../files/common/ca/example/*.crt"

clair_cert_file: "{{ inventory_dir }}/../../files/{{ inventory_name }}/clair/{{ clair_hostname }}.crt"
clair_key_file: "{{ inventory_dir }}/../../files/{{ inventory_name }}/clair/{{ clair_hostname }}.key"

# Wildcards accepted
# All filenames should be unique
clair_ca_files:
- "{{ inventory_dir }}/../../files/common/ca/example/*.crt"
