- name: "Restart Quay Registry Containers"
  hosts: quay
  gather_facts: no
  serial: 1
  tags:
    - quay
  tasks:
  # TODO: Knock out of load balancer
  - include_role:
      name: quay
      tasks_from: container-quay
  # TODO: Add back into load balancer

- name: "Restart Clair Scanner Containers"
  hosts: quay
  gather_facts: no
  serial: 1
  tags:
    - clair
  tasks:
  # TODO: Knock out of load balancer
  - include_role:
      name: quay
      tasks_from: container-clair
  # TODO: Add back into load balancer
