- name: Setup Redis Container
  hosts: redis
  gather_facts: no
  any_errors_fatal: yes
  tags:
  - redis
  vars:
    redis_data_dir: /var/data/redis
  tasks:
  - when: redis_runtime_user is defined
    block:
    - name: Get Redis User UID
      shell: "getent passwd {{ redis_runtime_user }} | cut -d ':' -f 3 || false"
      changed_when: false
      register: redis_runtime_uid_out
    - name: Setup user for Redis
      when: "redis_runtime_uid_out.stdout | default('') == ''"
      user:
        name: "{{ redis_runtime_user }}"
        system: yes
        home: /dev/null
        shell: /bin/false
        create_home: no
    - name: Get Redis User UID
      shell: "getent passwd {{ redis_runtime_user }} | cut -d ':' -f 3 || false"
      changed_when: false
      register: redis_runtime_uid_out
    - name: Set Redis User UID Fact
      set_fact:
        redis_runtime_uid: "{{ redis_runtime_uid_out.stdout }}"

  - name: Create Redis Container Directories
    tags:
    - folders
    file:
      path: "{{ redis_data_dir }}/{{ item }}"
      state: directory
      owner: "{{ redis_runtime_user | default(omit) }}"
      group: "{{ redis_runtime_user | default(omit) }}"
      mode: 0755
    with_items:
    - ''
    - data
  - name: Start Redis Container
    docker_container:
      name: redis
      user: "{{ redis_runtime_uid | default(omit) }}"
      restart: yes
      restart_policy: unless-stopped
      image: registry.redhat.io/rhscl/redis-32-rhel7:3.2
      published_ports:
      - 6379:6379
      env:
        REDIS_PASSWORD: "{{ quay_redis_password }}"
      state: started
      volumes:
      - "{{ redis_data_dir }}/data:/var/lib/redis/data:Z"
  - name: Wait for Redis Container
    delegate_to: localhost
    wait_for:
      host: "{{ inventory_hostname }}"
      port: 6379
      delay: 5
      timeout: 60
