# Merged on top of default API config response
# https://access.redhat.com/documentation/en-us/red_hat_quay/3/html/manage_red_hat_quay/quay-schema
ACTION_LOG_ARCHIVE_LOCATION: default
ACTION_LOG_ARCHIVE_PATH: /actionlog
ACTION_LOG_ROTATION_THRESHOLD: 2w

BUILDLOGS_REDIS: {host: "{{ quay_redis_hostname }}", password: "{{ quay_redis_password }}", port: "{{ quay_redis_port | default(6379) }}"}

LOG_ARCHIVE_LOCATION: default
FEATURE_ACTION_LOG_ROTATION: true
FEATURE_ANONYMOUS_ACCESS: true
FEATURE_APP_REGISTRY: false
FEATURE_APP_SPECIFIC_TOKENS: true
FEATURE_BUILD_SUPPORT: false
FEATURE_CHANGE_TAG_EXPIRATION: true
FEATURE_DIRECT_LOGIN: true
FEATURE_INVITE_ONLY_USER_CREATION: false
FEATURE_PARTIAL_USER_AUTOCOMPLETE: true
FEATURE_PROXY_STORAGE: true
FEATURE_REPO_MIRROR: "{{ quay_repomirror_feature }}"
FEATURE_REQUIRE_ENCRYPTED_BASIC_AUTH: true
FEATURE_REQUIRE_TEAM_INVITE: false
FEATURE_RESTRICTED_V1_PUSH: true
FEATURE_SECURITY_NOTIFICATIONS: true
FEATURE_SECURITY_SCANNER: true
FEATURE_USERNAME_CONFIRMATION: true
FEATURE_USER_CREATION: true
FEATURE_USER_LOG_ACCESS: true

PREFERRED_URL_SCHEME: https
REPO_MIRROR_TLS_VERIFY: true

SECURITY_SCANNER_ENDPOINT: "https://{{ clair_hostname }}:6060/"
SERVER_HOSTNAME: "{{ quay_hostname }}"
SETUP_COMPLETE: true

SUPER_USERS: "{{ quay_superusers }}"
TESTING: false

USERFILES_LOCATION: default
USERFILES_PATH: /userfiles

USER_EVENTS_REDIS: {host: "{{ quay_redis_hostname }}", password: "{{ quay_redis_password }}", port: "{{ quay_redis_port }}"}

