is_quay: false
is_clair: false

quay_storage_dir: /var/data/quay
quay_repomirror_storage_dir: /var/data/repomirror
quay_repomirror_feature: true

quay_image: quay.io/redhat/quay:v3.2.0
#quay_runtime_user: optional
quay_ca_files: []

quay_logo_file: ""

quay_hostname: CHANGEME
quay_cert_file: CHANGEME
quay_key_file: CHANGEME

quay_db_hostname: CHANGEME
quay_db_port: 5432
quay_db_username: CHANGEME
quay_db_password: CHANGEME
quay_db_dbname: CHANGEME
# quay_db_ca_file: optional

quay_db_admin_username: postgres
quay_db_admin_password: CHANGEME

quay_redis_port: 6379
quay_redis_password: CHANGEME

quay_initial_superuser_username: superuser
quay_initial_superuser_email: nobody@example.com
quay_initial_superuser_password: CHANGEME
quay_superusers:
- "{{ quay_initial_superuser_username }}"

clair_storage_dir: /var/data/clair
clair_image: quay.io/redhat/clair-jwt:v3.2.0
#clair_runtime_user: optional
clair_ca_files: []

clair_hostname: CHANGEME
clair_cert_file: CHANGEME
clair_key_file: CHANGEME

clair_db_hostname: CHANGEME
clair_db_port: 5432
clair_db_username: CHANGEME
clair_db_password: CHANGEME
clair_db_dbname: CHANGEME
# clair_db_ca_file: optional

clair_db_admin_username: postgres
clair_db_admin_password: CHANGEME

clair_pagination_key: "{{ lookup('password', '/tmp/clair_pagination_key length=32 chars=ascii_letters') }}"
clair_force_new_key: false
