- when:
  - quay_runtime_user is defined
  - quay_runtime_uid is not defined
  - is_quay
  tags:
  - always
  block:
  - name: Get Quay UID
    shell: "getent passwd {{ quay_runtime_user }} | cut -d ':' -f 3 || false"
    register: quay_runtime_uid_out
    changed_when: false
    failed_when: "quay_runtime_uid_out.stdout | default('') == ''"
  - name: Set Quay UID Fact
    set_fact:
      quay_runtime_uid: "{{ quay_runtime_uid_out.stdout }}"

- name: "Validate quay_setup_server is defined"
  assert:
    that: quay_setup_server is defined
    quiet: yes
- name: "Validate quay_setup_server is in list of servers"
  assert:
    that: quay_setup_server in ansible_play_hosts_all
    quiet: yes

- run_once: yes
  when: "inventory_hostname == quay_setup_server"
  block:
  - name: Quay Setup - Create Config Container
    docker_container:
      name: quay-config
      user: "{{ quay_runtime_uid | default(omit) }}"
      recreate: yes
      restart: no
      image: "{{ quay_image }}"
      command: "config {{ quay_setup_password }}"
      published_ports:
      - 8443:8443
      state: started
      env:
        RANDFILE: /tmp/.rnd
      volumes:
      - /tmp/quay-config:/conf/stack:z
  - name: Quay Setup - Copy DB CA File
    when: quay_db_ca_file is defined
    copy:
      src: "{{ quay_db_ca_file }}"
      dest: "/tmp/quay-config/database.pem"
