- when:
  - quay_runtime_user is defined
  - quay_runtime_uid is not defined
  - is_quay
  tags:
  - always
  block:
  - name: Get Quay UID
    shell: "getent passwd {{ quay_runtime_user }} | cut -d ':' -f 3 || false"
    register: quay_runtime_uid_out
    changed_when: false
    failed_when: "quay_runtime_uid_out.stdout | default('') == ''"
  - name: Set Quay UID Fact
    set_fact:
      quay_runtime_uid: "{{ quay_runtime_uid_out.stdout }}"

- when: is_quay
  tags:
  - containers
  block:
  - name: Create Quay Container
    docker_container:
      name: quay
      user: "{{ quay_runtime_uid | default(omit) }}"
      recreate: yes
      restart: yes
      restart_policy: unless-stopped
      image: "{{ quay_image }}"
      published_ports:
      - 443:8443
      - 80:8080
      sysctls:
        net.core.somaxconn: 4096
      state: started
      env:
        RANDFILE: /certificates/.rnd
      tmpfs:
      - /certificates
      - /etc/pki/ca-trust/extracted
      - /etc/pki/ca-trust/extracted/java
      - /etc/pki/ca-trust/extracted/openssl
      - /etc/pki/ca-trust/extracted/pem
      volumes:
      - "{{ quay_storage_dir }}/config:/conf/stack:z"
      - "{{ quay_storage_dir }}/storage:/datastorage:z"
      - "{{ quay_storage_dir }}/anchors:/etc/pki/ca-trust/source/anchors:z"
      - "{{ quay_storage_dir }}/custom:/quay-registry/static/img/logos/custom:z"
  - name: Create Quay Repomirror Container
    when: quay_repomirror_feature
    docker_container:
      name: repomirror
      user: "{{ quay_runtime_uid | default(omit) }}"
      recreate: yes
      restart: yes
      restart_policy: unless-stopped
      image: "{{ quay_image }}"
      published_ports: []
      sysctls:
        net.core.somaxconn: 4096
      state: started
      env:
        RANDFILE: /certificates/.rnd
      command: "repomirror"
      tmpfs:
      - /certificates
      - /etc/pki/ca-trust/extracted
      - /etc/pki/ca-trust/extracted/java
      - /etc/pki/ca-trust/extracted/openssl
      - /etc/pki/ca-trust/extracted/pem
      volumes:
      - "{{ quay_repomirror_storage_dir }}/config:/conf/stack:z"
      - "{{ quay_repomirror_storage_dir }}/storage:/datastorage:z"
      - "{{ quay_repomirror_storage_dir }}/anchors:/etc/pki/ca-trust/source/anchors:z"
      - "{{ quay_repomirror_storage_dir }}/custom:/quay-registry/static/img/logos/custom:z"

