- when:
  - clair_runtime_user is defined
  - clair_runtime_uid is not defined
  - is_clair
  tags:
  - always
  block:
  - name: Get Clair UID
    shell: "getent passwd {{ clair_runtime_user }} | cut -d ':' -f 3 || false"
    changed_when: false
    register: clair_runtime_uid_out
    failed_when: "clair_runtime_uid_out.stdout | default('') == ''"
  - name: Set Clair UID Fact
    set_fact:
      clair_runtime_uid: "{{ clair_runtime_uid_out.stdout }}"

- when: is_clair
  tags:
  - containers
  block:
  - name: Create Clair Container
    docker_container:
      name: clair
      user: "{{ clair_runtime_uid | default(omit) }}"
      recreate: yes
      restart: yes
      restart_policy: unless-stopped
      image: "{{ clair_image }}"
      published_ports:
      - 6060:6060
      - 6061:6061
      state: started
      env:
        RANDFILE: /certificates/.rnd
      tmpfs:
      - /certificates
      - /etc/pki/ca-trust/extracted
      - /etc/pki/ca-trust/extracted/java
      - /etc/pki/ca-trust/extracted/openssl
      - /etc/pki/ca-trust/extracted/pem
      volumes:
      - "{{ clair_storage_dir }}/clair/config:/clair/config:z"
      - "{{ clair_storage_dir }}/anchors:/etc/pki/ca-trust/source/anchors:z"

