- name: Determine Server Roles
  tags:
  - always
  set_fact:
    quay_servers: "{{ hostvars.values() | selectattr('is_quay', 'defined') | selectattr('is_quay') | map(attribute='inventory_hostname') | list }}"
    clair_servers: "{{ hostvars.values() | selectattr('is_clair', 'defined') | selectattr('is_clair') | map(attribute='inventory_hostname') | list }}"

- name: Check that Quay variables have been set
  when:
  - quay_servers | length > 0
  - "item.key.startswith('quay_')"
  assert:
    that: "{{ item.key }} != 'CHANGEME'"
    quiet: yes
  with_dict: "{{ lookup('file', 'defaults/main.yml') | from_yaml }}"
  loop_control:
    label: "{{ item.key }}"

- name: Check that Clair variables have been set
  when:
  - clair_servers | length > 0
  - "item.key.startswith('clair_')"
  assert:
    that: "{{ item.key }} != 'CHANGEME'"
    quiet: yes
  with_dict: "{{ lookup('file', 'defaults/main.yml') | from_yaml }}"
  loop_control:
    label: "{{ item.key }}"

- import_tasks: database.yml

- tags:
  - always
  block:
  - name: Set Quay DB sslmode default
    when: quay_db_sslmode is not defined
    set_fact:
      quay_db_sslmode: "{{ 'verify-full' if quay_db_ca_file is defined else 'prefer' }}"
  - name: Set Quay DB connect options without CA
    when: quay_db_ca_file is not defined
    set_fact:
      quay_db_connect_options:
        sslmode: "{{ quay_db_sslmode }}"
  - name: Set Quay DB connect options with CA
    when: quay_db_ca_file is defined
    set_fact:
      quay_db_connect_options:
        sslmode: "{{ quay_db_sslmode }}"
        sslrootcert: "/conf/stack/database.pem"

  - name: Set Clair DB sslmode default
    when: clair_db_sslmode is not defined
    set_fact:
      clair_db_sslmode: "{{ 'verify-full' if clair_db_ca_file is defined else 'require' }}"
  - name: Set Clair DB connect options without CA
    when: clair_db_ca_file is not defined
    set_fact:
      clair_db_connect_options: "sslmode={{ clair_db_sslmode }}"
  - name: Set Clair DB connect options with CA
    when: clair_db_ca_file is defined
    set_fact:
      clair_db_connect_options: "sslmode={{ clair_db_sslmode }},sslrootcert=/clair/config/database.pem"

- name: Create Quay Directories
  when: is_quay
  tags:
  - folders
  file:
    path: "{{ quay_storage_dir }}/{{ item }}"
    state: directory
    owner: "{{ quay_runtime_user | default(omit) }}"
    group: "{{ quay_runtime_user | default(omit) }}"
    mode: 0755
  with_items:
  - ''
  - config
  - custom
  - storage
  - anchors
- name: Create Quay Repomirror Directories
  when:
  - is_quay
  - quay_repomirror_feature
  tags:
  - folders
  file:
    path: "{{ quay_repomirror_storage_dir }}/{{ item }}"
    state: directory
    owner: "{{ quay_runtime_user | default(omit) }}"
    group: "{{ quay_runtime_user | default(omit)  }}"
    mode: 0755
  with_items:
  - config
  - custom
  - storage
  - anchors

- name: Create Clair Directories
  when: is_clair
  tags:
  - folders
  - clair
  file:
    path: "{{ clair_storage_dir }}/{{ item }}"
    state: directory
    owner: "{{ clair_runtime_user | default(omit)  }}"
    group: "{{ clair_runtime_user | default(omit)  }}"
    mode: 0755
  with_items:
  - ''
  - clair
  - clair/config
  - clair/config/keys
  - storage
  - anchors

- when: is_quay
  tags:
  - folders
  - quay
  - selinux
  block:
  - name: "Set selinux context for container data"
    sefcontext:
      target: "{{ item }}(/.*)?"
      setype: svirt_sandbox_file_t
      state: present
    register: sefcontext_status
    with_items:
    - "{{ quay_storage_dir }}"
  - name: "Apply selinux context for container data"
    when: sefcontext_status.changed
    shell: "restorecon -irv {{ item }}"
    with_items:
    - "{{ quay_storage_dir }}"

- when:
  - is_quay
  - quay_repomirror_feature
  tags:
  - folders
  - quay
  - selinux
  block:
  - name: "Set selinux context for container data"
    sefcontext:
      target: "{{ item }}(/.*)?"
      setype: svirt_sandbox_file_t
      state: present
    register: sefcontext_status
    with_items:
    - "{{ quay_repomirror_storage_dir }}"
  - name: "Apply selinux context for container data"
    when: sefcontext_status.changed
    shell: "restorecon -irv {{ item }}"
    with_items:
    - "{{ quay_repomirror_storage_dir }}"

- when: is_clair
  tags:
  - folders
  - clair
  - selinux
  block:
  - name: "Set selinux context for container data"
    sefcontext:
      target: "{{ item }}(/.*)?"
      setype: svirt_sandbox_file_t
      state: present
    register: sefcontext_status
    with_items:
    - "{{ clair_storage_dir }}"
  - name: "Apply selinux context for container data"
    when: sefcontext_status.changed
    shell: "restorecon -irv {{ item }}"
    with_items:
    - "{{ clair_storage_dir }}"

# Here we gather: quay_config_merged, quay_api_scanner_key_id, quay_api_scanner_key_data
- import_tasks: setup.yml

- name: Validate Setup Variables - Clair
  when: is_clair
  assert: 
    that: "{{ item }} | default('') != ''"
    quiet: yes
  with_items:
  - quay_api_scanner_key_id

- name: Validate Setup Variables - Quay
  when: is_quay
  assert:
    that: "{{ item }} | default('') != ''"
    quiet: yes
  with_items:
  - quay_config_merged

- when: is_quay
  block:
  - name: Init Custom Logo Config
    set_fact:
      quay_config_custom_logo: {}
  - name: Update Quay Config with Custom Logo
    when: quay_logo_file != ''
    set_fact:
      quay_config_custom_logo:
        ENTERPRISE_LOGO_URL: "/static/img/logos/custom/{{ quay_logo_file|basename }}"

- when: is_quay
  block:
  - name: Write Merged Quay Config
    copy:
      dest: "{{ quay_storage_dir }}/config/config.yaml"
      content: "{{ quay_config_merged | combine(quay_config_custom_logo) | to_nice_yaml }}"
      backup: yes
  - name: Copy Quay TLS Cert File
    tags:
    - cert
    copy:
      dest: "{{ quay_storage_dir }}/config/ssl.cert"
      src: "{{ quay_cert_file }}"
  - name: Copy Quay TLS Key File
    tags:
    - cert
    copy:
      dest: "{{ quay_storage_dir }}/config/ssl.key"
      src: "{{ quay_key_file }}"
  - name: Copy CA Files for Quay
    tags:
    - ca
    copy:
      dest: "{{ quay_storage_dir }}/anchors/{{ item | basename | regex_replace('\\.[^\\.]$','.crt') }}"
      src: "{{ item }}"
    with_fileglob: "{{ quay_ca_files }}"
  - name: Copy DB CA File for Quay
    tags:
    - ca
    when: quay_db_ca_file is defined
    copy:
      src: "{{ quay_db_ca_file }}"
      dest: "{{ quay_storage_dir }}/config/database.pem"
  - name: Copy Custom Logo File for Quay
    tags:
    - logo
    when: quay_logo_file != ''
    copy:
      src: "{{ quay_logo_file }}"
      dest: "{{ quay_storage_dir }}/custom/{{ quay_logo_file | basename }}"

- when:
  - is_quay
  - quay_repomirror_feature
  block:
  - name: Write Merged Quay Repomirror Config
    copy:
      dest: "{{ quay_repomirror_storage_dir }}/config/config.yaml"
      content: "{{ quay_config_merged | combine(quay_config_custom_logo) | to_nice_yaml }}"
      backup: yes
  - name: Copy Quay Repomirror TLS Cert File
    tags:
    - cert
    copy:
      dest: "{{ quay_repomirror_storage_dir }}/config/ssl.cert"
      src: "{{ quay_cert_file }}"
  - name: Copy Quay Repomirror TLS Key File
    tags:
    - cert
    copy:
      dest: "{{ quay_repomirror_storage_dir }}/config/ssl.key"
      src: "{{ quay_key_file }}"
  - name: Copy CA Files for Quay Repomirror
    tags:
    - ca
    copy:
      dest: "{{ quay_repomirror_storage_dir }}/anchors/{{ item | basename | regex_replace('\\.[^\\.]$','.crt') }}"
      src: "{{ item }}"
    with_fileglob: "{{ quay_ca_files }}"
  - name: Copy DB CA File for Quay Repomirror
    tags:
    - ca
    when: quay_db_ca_file is defined
    copy:
      src: "{{ quay_db_ca_file }}"
      dest: "{{ quay_repomirror_storage_dir }}/config/database.pem"
  - name: Copy Custom Logo File for Quay Repomirror
    tags:
    - logo
    when: quay_logo_file != ''
    copy:
      src: "{{ quay_logo_file }}"
      dest: "{{ quay_repomirror_storage_dir }}/custom/{{ quay_logo_file | basename }}"

- when: is_clair
  block:
  - name: Create Clair Scanner Keyfile
    when: "quay_api_scanner_key_data | default('') != ''"
    copy:
      dest: "{{ clair_storage_dir }}/clair/config/keys/{{ quay_api_scanner_key_id }}.pem"
      content: "{{ quay_api_scanner_key_data }}"
  - name: Verify Clair Scanner Keyfile Exists
    stat:
      path: "{{ clair_storage_dir }}/clair/config/keys/{{ quay_api_scanner_key_id }}.pem"
    register: clair_keyfile
    failed_when: "not clair_keyfile.stat.exists"
  - name: Get Clair Config from Role
    include_vars:
      file: files/clair/config.yaml
      name: clair_role_config
  - name: Write Clair Config
    copy:
      dest: "{{ clair_storage_dir }}/clair/config/config.yaml"
      content: "{{ clair_role_config | to_nice_yaml }}"
      backup: yes
  - name: Copy Clair TLS Cert File
    tags:
    - cert
    copy:
      dest: "{{ clair_storage_dir }}/clair/config/ssl.cert"
      src: "{{ clair_cert_file }}"
  - name: Copy Clair TLS Key File
    tags:
    - cert
    copy:
      dest: "{{ clair_storage_dir }}/clair/config/ssl.key"
      src: "{{ clair_key_file }}"
  - name: Copy CA Files for Clair
    tags:
    - ca
    copy:
      dest: "{{ clair_storage_dir }}/anchors/{{ item | basename | regex_replace('\\.[^\\.]$','.crt') }}"
      src: "{{ item }}"
    with_fileglob: "{{ clair_ca_files }}"
  - name: Copy DB CA File for Clair
    tags:
    - ca
    when: clair_db_ca_file is defined
    copy:
      src: "{{ clair_db_ca_file }}"
      dest: "{{ clair_storage_dir }}/clair/config/database.pem"

# Start Quay Containers
- import_tasks: container-quay.yml

# Start Clair Containers
- import_tasks: container-clair.yml
